--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.1.1113
--   Created On : пятница, 03 Апрель, 2015 
--   DBMS       : SQL Server 2008 
--   -------------------------------------------------- 


--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Staff.FK_Employee_Department') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Staff.Employee DROP CONSTRAINT FK_Employee_Department
;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Staff.Department') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Staff.Department
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Staff.Employee') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Staff.Employee
;


--  Create Tables 
CREATE TABLE Staff.Department ( 
	Id bigint NOT NULL,
	FullName nvarchar(1000) NOT NULL,
	ShortName nvarchar(100) NOT NULL,
	SourceId bigint NOT NULL,
	Timestamp datetime2(7) NULL
)
;

CREATE TABLE Staff.Employee ( 
	Id bigint NOT NULL,
	FirstName nvarchar(100) NOT NULL,
	LastName nvarchar(100) NOT NULL,
	Birthday date NOT NULL,
	SourceId bigint NOT NULL,
	Timestamp datetime2(7) NULL,
	DepartmentId bigint NULL
)
;


--  Create Primary Key Constraints 
ALTER TABLE Staff.Department ADD CONSTRAINT PK_Department 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE Staff.Employee ADD CONSTRAINT PK_Employee 
	PRIMARY KEY CLUSTERED (Id)
;



--  Create Foreign Key Constraints 
ALTER TABLE Staff.Employee ADD CONSTRAINT FK_Employee_Department 
	FOREIGN KEY (DepartmentId) REFERENCES Staff.Department (Id)
;
