--   -------------------------------------------------- 
--   Generated by Enterprise Architect Version 11.1.1113
--   Created On : пятница, 03 Апрель, 2015 
--   DBMS       : SQL Server 2008 
--   -------------------------------------------------- 


--  Drop Foreign Key Constraints 
IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Source.FK_Employee_Department') AND OBJECTPROPERTY(id, 'IsForeignKey') = 1)
ALTER TABLE Source.Employee DROP CONSTRAINT FK_Employee_Department
;


--  Drop Tables, Stored Procedures and Views 

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Source.Department') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Source.Department
;

IF EXISTS (SELECT * FROM dbo.sysobjects WHERE id = object_id('Source.Employee') AND  OBJECTPROPERTY(id, 'IsUserTable') = 1)
DROP TABLE Source.Employee
;


--  Create Tables 
CREATE TABLE Source.Department ( 
	FullName nvarchar(1000) NOT NULL,
	ShortName nvarchar(100) NOT NULL,
	Id bigint NOT NULL
)
;

CREATE TABLE Source.Employee ( 
	FirstName nvarchar(100) NOT NULL,
	LastName nvarchar(100) NOT NULL,
	Hired date NOT NULL,
	Fired date NOT NULL,
	Birthday date NOT NULL,
	Id bigint NOT NULL,
	DepartmentId bigint NULL
)
;


--  Create Primary Key Constraints 
ALTER TABLE Source.Department ADD CONSTRAINT PK_Department 
	PRIMARY KEY CLUSTERED (Id)
;

ALTER TABLE Source.Employee ADD CONSTRAINT PK_Employee 
	PRIMARY KEY CLUSTERED (Id)
;



--  Create Foreign Key Constraints 
ALTER TABLE Source.Employee ADD CONSTRAINT FK_Employee_Department 
	FOREIGN KEY (DepartmentId) REFERENCES Source.Department (Id)
;
